# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ github.workspace }}/SimpleFeedReader/SimpleFeedReader.csproj --no-restore
    - name: Test
      run: dotnet test ${{ github.workspace }}/SimpleFeedReader/SimpleFeedReader.csproj --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ${{ github.workspace }}/SimpleFeedReader/SimpleFeedReader.csproj -c Release -o website
    - name: copy scripts
      run: dir
      shell: powershell
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: SimpleFeedReader/website/
        if-no-files-found: error
